version: '3'

services:
  db:
    build: .
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
    driver: local
